AWSTemplateFormatVersion: '2010-09-09'
Description: >
  MedEquip Cloud Infrastructure with MDB and MApp VPCs, VPC Peering, Routing,
  Security Groups, and a Bastion Host to access MDB VPC's private resources.

Resources:

  ### MDB VPC and Subnets
  MDBVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MDB-VPC

  MDBPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MDBVPC
      CidrBlock: 10.10.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: MDB-Private-Subnet-1

  MDBPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MDBVPC
      CidrBlock: 10.10.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: MDB-Private-Subnet-2

  MDBPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MDBVPC
      Tags:
        - Key: Name
          Value: MDB-Private-RouteTable

  MDBPrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MDBPrivateSubnet1
      RouteTableId: !Ref MDBPrivateRouteTable

  MDBPrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MDBPrivateSubnet2
      RouteTableId: !Ref MDBPrivateRouteTable

  ### MApp VPC and Subnets
  MAppVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.20.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: M-App-VPC

  MAppPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MAppVPC
      CidrBlock: 10.20.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: MApp-Public-Subnet-1

  MAppInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MApp-IGW

  MAppAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MAppVPC
      InternetGatewayId: !Ref MAppInternetGateway

  MAppPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MAppVPC
      Tags:
        - Key: Name
          Value: MApp-Public-RouteTable

  MAppPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: MAppAttachGateway
    Properties:
      RouteTableId: !Ref MAppPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MAppInternetGateway

  MAppPublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MAppPublicSubnet1
      RouteTableId: !Ref MAppPublicRouteTable

  ### VPC Peering
  VPCPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !Ref MDBVPC
      PeerVpcId: !Ref MAppVPC
      Tags:
        - Key: Name
          Value: MDB-MApp-Peering

  MDBToMAppPeeringRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref MDBPrivateRouteTable
      DestinationCidrBlock: 10.20.0.0/16
      VpcPeeringConnectionId: !Ref VPCPeeringConnection

  MAppPublicToMDBPeeringRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref MAppPublicRouteTable
      DestinationCidrBlock: 10.10.0.0/16
      VpcPeeringConnectionId: !Ref VPCPeeringConnection

  ### Security Group for MDB (Optional; retained for internal SSH if needed)
  MDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from MApp VPC
      VpcId: !Ref MDBVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.20.0.0/16

  ### Simplified Bastion Host (no security group or key setup)
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 (verify region)
      SubnetId: !Ref MAppPublicSubnet1
      Tags:
        - Key: Name
          Value: BastionHost

Outputs:
  BastionHostPublicIP:
    Description: Public IP of the Bastion Host
    Value: !GetAtt BastionHost.PublicIp
