AWSTemplateFormatVersion: '2010-09-09'
Description: >
  MedEquip Cloud Infrastructure with MApp VPC and
  Bastion Host + Two Web Servers with Apache installed.
  Instances connected to MApp public subnets (one in each AZ).
  Security groups excluded for manual setup later.

Resources:

  ### MApp VPC and Subnets (same as your original)
  MAppVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.20.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: M-App-VPC

  MAppPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MAppVPC
      CidrBlock: 10.20.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: MApp-Public-Subnet-1

  MAppPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MAppVPC
      CidrBlock: 10.20.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: MApp-Public-Subnet-2

  MAppInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MApp-IGW

  MAppAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MAppVPC
      InternetGatewayId: !Ref MAppInternetGateway

  MAppPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MAppVPC
      Tags:
        - Key: Name
          Value: MApp-Public-RouteTable

  MAppPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: MAppAttachGateway
    Properties:
      RouteTableId: !Ref MAppPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MAppInternetGateway

  MAppPublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MAppPublicSubnet1
      RouteTableId: !Ref MAppPublicRouteTable

  MAppPublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MAppPublicSubnet2
      RouteTableId: !Ref MAppPublicRouteTable

  ### Bastion Host Instance (no SG, fixed key pair 'vockey.pem')
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: vockey.pem
      SubnetId: !Ref MAppPublicSubnet1
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 (update if needed)
      Tags:
        - Key: Name
          Value: BastionHost

  ### Web Server 1 in AZ1 with Apache
  MAppWebServer1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: vockey.pem
      SubnetId: !Ref MAppPublicSubnet1
      ImageId: ami-0c02fb55956c7d316
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
      Tags:
        - Key: Name
          Value: MApp-WebServer-1

  ### Web Server 2 in AZ2 with Apache
  MAppWebServer2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: vockey.pem
      SubnetId: !Ref MAppPublicSubnet2
      ImageId: ami-0c02fb55956c7d316
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
      Tags:
        - Key: Name
          Value: MApp-WebServer-2

Outputs:
  BastionHostId:
    Description: Instance ID of Bastion Host
    Value: !Ref BastionHost

  WebServer1Id:
    Description: Instance ID of MApp Web Server 1
    Value: !Ref MAppWebServer1

  WebServer2Id:
    Description: Instance ID of MApp Web Server 2
    Value: !Ref MAppWebServer2
