AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template with Apache installed on EC2 instances in VPC-11 setup

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances

Resources:
  # VPCs
  VPC11A:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 11.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-11A

  VPC11B:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 11.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-11B

  # Internet Gateways
  InternetGateway11A:
    Type: AWS::EC2::InternetGateway

  InternetGatewayAttachment11A:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC11A
      InternetGatewayId: !Ref InternetGateway11A

  InternetGateway11B:
    Type: AWS::EC2::InternetGateway

  InternetGatewayAttachment11B:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC11B
      InternetGatewayId: !Ref InternetGateway11B

  # Public Subnets
  PublicSubnet11A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC11A
      CidrBlock: 11.0.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public-11A

  PublicSubnet11B:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC11B
      CidrBlock: 11.1.1.0/24
      AvailabilityZone: !Select [ 1, !GetAZs "" ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public-11B

  # Route Tables and Associations
  RouteTable11A:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC11A

  Route11A:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment11A
    Properties:
      RouteTableId: !Ref RouteTable11A
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway11A

  SubnetRouteTableAssociation11A:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet11A
      RouteTableId: !Ref RouteTable11A

  RouteTable11B:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC11B

  Route11B:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment11B
    Properties:
      RouteTableId: !Ref RouteTable11B
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway11B

  SubnetRouteTableAssociation11B:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet11B
      RouteTableId: !Ref RouteTable11B

  # Security Groups
  InstanceSG11A:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP
      VpcId: !Ref VPC11A
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  InstanceSG11B:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP
      VpcId: !Ref VPC11B
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # IAM Instance Profile
  LabInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [ "LabRole" ]

  # EC2 Instances with Apache Installation
  EC2Instance11A:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c55b159cbfafe1f0
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet11A
      SecurityGroupIds:
        - !Ref InstanceSG11A
      IamInstanceProfile: !Ref LabInstanceProfile
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: EC2-11A
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html><h1>Hello from EC2-11A (Apache Web Server)</h1></html>" > /var/www/html/index.html

  EC2Instance11B:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c55b159cbfafe1f0
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet11B
      SecurityGroupIds:
        - !Ref InstanceSG11B
      IamInstanceProfile: !Ref LabInstanceProfile
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: EC2-11B
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html><h1>Hello from EC2-11B (Apache Web Server)</h1></html>" > /var/www/html/index.html
