AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy two VPCs with Apache-installed EC2 instances (no instance profile used)

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access

Resources:
  # VPCs
  VPC11A:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 11.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-11A

  VPC11B:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 11.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-11B

  # Internet Gateways
  InternetGateway11A:
    Type: AWS::EC2::InternetGateway

  AttachIGW11A:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC11A
      InternetGatewayId: !Ref InternetGateway11A

  InternetGateway11B:
    Type: AWS::EC2::InternetGateway

  AttachIGW11B:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC11B
      InternetGatewayId: !Ref InternetGateway11B

  # Public Subnets
  PublicSubnet11A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC11A
      CidrBlock: 11.0.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public-11A

  PublicSubnet11B:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC11B
      CidrBlock: 11.1.1.0/24
      AvailabilityZone: !Select [ 1, !GetAZs "" ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public-11B

  # Route Tables and Routes
  RouteTable11A:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC11A

  Route11A:
    Type: AWS::EC2::Route
    DependsOn: AttachIGW11A
    Properties:
      RouteTableId: !Ref RouteTable11A
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway11A

  SubnetRouteTableAssociation11A:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet11A
      RouteTableId: !Ref RouteTable11A

  RouteTable11B:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC11B

  Route11B:
    Type: AWS::EC2::Route
    DependsOn: AttachIGW11B
    Properties:
      RouteTableId: !Ref RouteTable11B
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway11B

  SubnetRouteTableAssociation11B:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet11B
      RouteTableId: !Ref RouteTable11B

  # Security Groups
  WebServerSG11A:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      VpcId: !Ref VPC11A
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServerSG11B:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      VpcId: !Ref VPC11B
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # EC2 Instances with Apache and PHP (no instance profile used)
  WebServer11A:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      ImageId: ami-0a5c3558529277641  # Amazon Linux 2 in most regions
      SubnetId: !Ref PublicSubnet11A
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref WebServerSG11A
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd php php-mysql
          systemctl start httpd
          systemctl enable httpd
          echo "<?php phpinfo(); ?>" > /var/www/html/index.php

  WebServer11B:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      ImageId: ami-0a5c3558529277641  # Amazon Linux 2 in most regions
      SubnetId: !Ref PublicSubnet11B
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref WebServerSG11B
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd php php-mysql
          systemctl start httpd
          systemctl enable httpd
          echo "<?php phpinfo(); ?>" > /var/www/html/index.php

Outputs:
  PublicIP11A:
    Description: Public IP of EC2 in VPC11A
    Value: !GetAtt WebServer11A.PublicIp

  PublicIP11B:
    Description: Public IP of EC2 in VPC11B
    Value: !GetAtt WebServer11B.PublicIp
